### ISSUE TITLE
Unable to encase shafts with copper glass/clear glass casings

### ISSUE THREAD

**Issue by Starwhip** [NovaStarter/Create-Crystal-Clear#10]
While the other casings can encase shafts, the copper variants cannot. Are these intended to only work with pipes (in a later release?)

**Comment by Cyvack** [comment]
Copper glass casings are intended to only work with encasing fluid pipes, just like in base create (And will be in a later release, yes). This is done for consistency with the base mod (And by extension, I will add the ability to encase shafts / cogs with train casings as well, whenever I get the time to do so).
