### ISSUE TITLE
No load Game with new version of Create Mod

### ISSUE THREAD

**Issue by 5stigma** [NovaStarter/Create-Crystal-Clear#12]
crash with new version of Create Mod

**Comment by Cyvack** [comment]
Can you send the crash report

**Comment by 5stigma** [comment]
no drop crash report, only displayed not load screen

**Comment by 5stigma** [comment]
[crash-2022-12-14_16.16.28-fml.txt](https://github.com/NovaStarter/Create-Crystal-Clear/files/10232364/crash-2022-12-14_16.16.28-fml.txt)
 This?

**Comment by Cyvack** [comment]
It seems to be an incompatibility between create: enchantment industries and my mod. Try deleting enchantment industries and see if it loads
