### ISSUE TITLE
Steel Textures not loading 1.19.2 with alloyed installed

### ISSUE THREAD

**Issue by zachsai** [NovaStarter/Create-Crystal-Clear#13]
![image](https://user-images.githubusercontent.com/63996164/208763960-9b6cb854-9ab8-40a0-9d00-345ae8ed4d6e.png)
The textures are not loading properly with alloyed installed
Minecraft 1.19.2
Forge: 43.1.52
Alloyed: v1.5
Crystal Clear: 0.1.1e

**Comment by Cyvack** [comment]
Fixed in an update that is currently under review by curse
