### ISSUE TITLE
Wrench Pickup doesn't work

### ISSUE THREAD

**Issue by ItoKyoshiro** [NovaStarter/Create-Crystal-Clear#15]
version: create_crystal_clear-0.1.3e-1.18.2 (Create: create-1.18.2-0.5.0.g)

If I place the Glass Casing into the world can't pick up by Sneak + Right Click with a Wrench like the default casings.
I tried adding the Block Tag create:wrench_pickup (with CraftTweaker) to force this behaviour but with this the Glass Casing disappear instead of going into my inventory

PS: Awesome mod! <3

**Comment by Cyvack** [comment]
Will be fixed when I re-write the mod
