### ISSUE TITLE
Create: Ender Transmission imcompatiable

### ISSUE THREAD

**Issue by furuochen-dev** [NovaStarter/Create-Crystal-Clear#19]
Adding this mod will cause weird behaviors on kinetic energy transmitter
I don't know why but removing this fixes the bug

btw im ender transmission dev

**Comment by Cyvack** [comment]
Unsure what would be causing bugs with your mod. I do plan on re-writing CC eventually when create pushes an update containing a PR that I made, but it is unknown how long that will be.
