### ISSUE TITLE
Wrench does not interact with Glass Casings

### ISSUE THREAD

**Issue by Ebkrem** [NovaStarter/Create-Crystal-Clear#24]
Unable to pick up glass casings with Create "Wrench" tool shift-right click.
Behavior inconsistent with other casing blocks in Create.

**Mod version:** 0.1.2e
**Minecraft version:** 1.19.2
**Forge version:** 43.2.3

If this is an intentional choice, a config setting option to enable the behavior would be preferred.

**Comment by Cyvack** [comment]
Has been fixed 👍
