### ISSUE TITLE
Key Conflict

### ISSUE THREAD

**Issue by Dr-WeiAL** [NovaStarter/Create-Crystal-Clear#29]
Hi, I found that the itemGroup key in the language file of this mod is not specific to this mod, which will cause conflicts with the keys of other mods, I suggest you change "itemGroup.main_group" to "itemGroup.create_crystal_clear"
![image](https://github.com/NovaStarter/Create-Crystal-Clear/assets/47446553/a144297c-e75c-4985-b17a-4e479e3f3485)

**Comment by Cyvack** [comment]
I'll make sure to fix that, thanks for bring it to my attention
