### ISSUE TITLE
doesnt work with the latest version of create

### ISSUE THREAD

**Issue by linkhidalgogato** [NovaStarter/Create-Crystal-Clear#4]
the mod asks for Create 1.18.2 v0.5.0c instead of the latest version (Create 1.18.2 v0.5.0d) which crashes the game

**Comment by JieningYu** [comment]
It actually works but the mods.toml needs to be updated.

**Comment by Cyvack** [comment]
It does work with the latest version of create, and the mods.toml is fine 
It's just that curse was downloading the incorrect version of the mod (As it set the 0.5c version as the main file, which is what loaders will use to download the mod) 
That should be fixed
