### ISSUE TITLE
PROBLEMA AL INSTALAR EL MOD POR CURSEFORGE

### ISSUE THREAD

**Issue by d-rick** [NovaStarter/Create-Crystal-Clear#6]
Al instalar el mod a través de la aplicación **CURSEFORGE** para la versión 1.19.2 también descarga **"flywheel"** que aún no está para la 1.19 lo que da un error.
el mod solo funciona perfectamente en 1.19.2

**Comment by Cyvack** [comment]
Hopefully this has been fixed, as I haven't had any issues with 1.19.2 autodownloading flywheel since I did some changes.
